version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      AWS_ACCESS_KEY: your_aws_access_key
      AWS_SECRET_KEY: your_aws_secret_key
      S3_BUCKET_NAME: your_s3_bucket_name
